//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        public string CompanyName { get; set; }
        public string AgentType { get; set; }
        public string LegalAddress { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string DirectorName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string Logo { get; set; }
        public Nullable<int> SupplyPriority { get; set; }
        public string SalesHistory { get; set; }
        public int AgentID { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
