//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string AgentName { get; set; }
        public Nullable<System.DateTime> RealisationDate { get; set; }
        public Nullable<int> QuantityProduction { get; set; }
        public string ProductType { get; set; }
        public string ArticleNumber { get; set; }
        public Nullable<int> ProductionPersonnelCount { get; set; }
        public string ProductionDepartment { get; set; }
        public string MinimumAgentPrice { get; set; }
    
        public virtual Agents Agents { get; set; }
    }
}
